version: '3'
  
services:
    redis:
        image: "redis"
        ports:
            - "6379:6379"
            
    rabbitmq:
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_VHOST: "backoffice"
            RABBITMQ_DEFAULT_PASS: "admin123"
        ports:
            - "15672:15672"
            - "5672:5672"
            
    mysql:
        image: "mysql:latest"
        environment:
            MYSQL_ROOT_PASSWORD: "mysql"
            MYSQL_ALLOW_EMPTY_PASSWORD: "false"
        ports:
            - "3306:3306"
        volumes:
            - "/home/oswald/.data/mysql:/var/lib/mysql"
            
    postgres-db:
        image: "postgres" # use latest official postgres version
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - "5432:5432"
        volumes:
            - "/home/oswald/.data/postgres:/var/lib/postgresql/data/"
            
    mariadb:
        image: "mariadb"
        environment:
            MYSQL_ROOT_PASSWORD: "mariadb"
            MYSQL_ALLOW_EMPTY_PASSWORD: "false"
        ports:
            - "33060:3306"
        volumes:
            - "/home/oswald/.data/mariadb:/var/lib/mysql"
