info:
  description:  to handle  the information client
  version: "v1"
  title: onboarding-cross-external-authentication
schemes:
  - "http"
tags:
- name: "client"
  description: "Client"
swagger: "2.0"
servers:
  - url: http://localhost:3000/v1
    description: Local
  - url: https://payments-wallet-qa.fif.tech/api/onboarding/v1
    description: QA
