info:
  description: Documentation api user for usame app
  version: "v1"
  title: user-api
schemes:
  - "http"
tags:
- name: "user"
  description: "User"
swagger: "2.0"
servers:
  - url: http://localhost:3000/v1
    description: Local
